version: '3.8'
services:
  mongo-db:
    image: mongo:7.0.9
    restart: always
    container_name: mongo-db-noc
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db